version: "3.9"
services:
  streamlit:
    container_name: streamlit
    build:
      context: ./
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_TYPE=openai
      - OPENAI_COMPLETIONS_ENGINE=text-davinci-003
      - OPENAI_EMBEDDINGS_ENGINE=text-embedding-ada-002
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TYPE=standard
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:
  redis_data:
